WebTestCreator/Flask/flask_website/views/general.py
from flask import Blueprint, render_template, session, redirect, url_for, \
     request, flash, g, jsonify, abort
from flask_openid import COMMON_PROVIDERS
from flask_website import oid
from flask_website.search import search as perform_search
from flask_website.utils import requires_login, request_wants_json
from flask_website.database import db_session, User
from flask_website.listings.releases import releases

mod = Blueprint('general', __name__)


@mod.route('/')
def index():
    if request_wants_json():
        return jsonify(releases=[r.to_json() for r in releases])

    return render_template(
        'general/index.html',
        latest_release=releases[-1],
        # pdf link does not redirect, needs version
        # docs version only includes major.minor
        docs_pdf_version='.'.join(releases[-1].version.split('.', 2)[:2])
    )


@mod.route('/search/')
def search():
    q = request.args.get('q') or ''
    page = request.args.get('page', type=int) or 1
    results = None
    if q:
        results = perform_search(q, page=page)
        if results is None:
            abort(404)
    return render_template('general/search.html', results=results, q=q)


@mod.route('/logout/')
def logout():
    if 'openid' in session:
        flash(u'Logged out')
        del session['openid']
    return redirect(request.referrer or url_for('general.index'))


@mod.route('/login/', methods=['GET', 'POST'])
@oid.loginhandler
def login():
    if g.user is not None:
        return redirect(url_for('general.index'))
    if 'cancel' in request.form:
        flash(u'Cancelled. The OpenID was not changed.')
        return redirect(oid.get_next_url())
    openid = request.values.get('openid')
    if not openid:
        openid = COMMON_PROVIDERS.get(request.args.get('provider'))
    if openid:
        return oid.try_login(openid, ask_for=['fullname', 'nickname'])
    error = oid.fetch_error()
    if error:
        flash(u'Error: ' + error)
    return render_template('general/login.html', next=oid.get_next_url())


@mod.route('/first-login/', methods=['GET', 'POST'])
def first_login():
    if g.user is not None or 'openid' not in session:
        return redirect(url_for('.login'))
    if request.method == 'POST':
        if 'cancel' in request.form:
            del session['openid']
            flash(u'Login was aborted')
            return redirect(url_for('general.login'))
        db_session.add(User(request.form['name'], session['openid']))
        db_session.commit()
        flash(u'Successfully created profile and logged in')
        return redirect(oid.get_next_url())
    return render_template('general/first_login.html',
                           next=oid.get_next_url(),
                           openid=session['openid'])


@mod.route('/profile/', methods=['GET', 'POST'])
@requires_login
def profile():
    name = g.user.name
    if request.method == 'POST':
        name = request.form['name'].strip()
        if not name:
            flash(u'Error: a name is required')
        else:
            g.user.name = name
            db_session.commit()
            flash(u'User profile updated')
            return redirect(url_for('.index'))
    return render_template('general/profile.html', name=name)


@mod.route('/profile/change-openid/', methods=['GET', 'POST'])
@requires_login
@oid.loginhandler
def change_openid():
    if request.method == 'POST':
        if 'cancel' in request.form:
            flash(u'Cancelled. The OpenID was not changed.')
            return redirect(oid.get_next_url())
    openid = request.values.get('openid')
    if not openid:
        openid = COMMON_PROVIDERS.get(request.args.get('provider'))
    if openid:
        return oid.try_login(openid)
    error = oid.fetch_error()
    if error:
        flash(u'Error: ' + error)
    return render_template('general/change_openid.html',
                           next=oid.get_next_url())


@oid.after_login
def create_or_login(resp):
    session['openid'] = resp.identity_url
    user = g.user or User.query.filter_by(openid=resp.identity_url).first()
    if user is None:
        return redirect(url_for('.first_login', next=oid.get_next_url(),
                                name=resp.fullname or resp.nickname))
    if user.openid != resp.identity_url:
        user.openid = resp.identity_url
        db_session.commit()
        flash(u'OpenID identity changed')
    else:
        flash(u'Successfully signed in')
    return redirect(oid.get_next_url())

WebTestCreator/Flask/flask_website/views/snippets.py
# -*- coding: utf-8 -*-
from urlparse import urljoin
from flask import Blueprint, render_template, request, flash, abort, redirect, \
     g, url_for, jsonify
from werkzeug.contrib.atom import AtomFeed
from flask_website.utils import requires_login, requires_admin, \
     format_creole, request_wants_json
from flask_website.database import Category, Snippet, Comment, db_session

mod = Blueprint('snippets', __name__, url_prefix='/snippets')


@mod.route('/')
def index():
    return render_template('snippets/index.html',
        categories=Category.query.order_by(Category.name).all(),
        recent=Snippet.query.order_by(Snippet.pub_date.desc()).limit(5).all())


@mod.route('/new/', methods=['GET', 'POST'])
@requires_login
def new():
    category_id = None
    preview = None
    if 'category' in request.args:
        rv = Category.query.filter_by(slug=request.args['category']).first()
        if rv is not None:
            category_id = rv.id
    if request.method == 'POST':
        category_id = request.form.get('category', type=int)
        if 'preview' in request.form:
            preview = format_creole(request.form['body'])
        else:
            title = request.form['title']
            body = request.form['body']
            if not body:
                flash(u'Error: you have to enter a snippet')
            else:
                category = Category.query.get(category_id)
                if category is not None:
                    snippet = Snippet(g.user, title, body, category)
                    db_session.add(snippet)
                    db_session.commit()
                    flash(u'Your snippet was added')
                    return redirect(snippet.url)
    return render_template('snippets/new.html',
        categories=Category.query.order_by(Category.name).all(),
        active_category=category_id, preview=preview)


@mod.route('/<int:id>/', methods=['GET', 'POST'])
def show(id):
    snippet = Snippet.query.get(id)
    if snippet is None:
        abort(404)
    if request_wants_json():
        return jsonify(snippet=snippet.to_json())
    if request.method == 'POST':
        title = request.form['title']
        text = request.form['text']
        if text:
            db_session.add(Comment(snippet, g.user, title, text))
            db_session.commit()
            flash(u'Your comment was added')
            return redirect(snippet.url)
    return render_template('snippets/show.html', snippet=snippet)


@mod.route('/comments/<int:id>/', methods=['GET', 'POST'])
@requires_admin
def edit_comment(id):
    comment = Comment.query.get(id)
    if comment is None:
        abort(404)
    form = dict(title=comment.title, text=comment.text)
    if request.method == 'POST':
        if 'delete' in request.form:
            db_session.delete(comment)
            db_session.commit()
            flash(u'Comment was deleted.')
            return redirect(comment.snippet.url)
        elif 'cancel' in request.form:
            return redirect(comment.snippet.url)
        form['title'] = request.form['title']
        form['text'] = request.form['text']
        if not form['text']:
            flash(u'Error: comment text is required.')
        else:
            comment.title = form['title']
            comment.text = form['text']
            db_session.commit()
            flash(u'Comment was updated.')
            return redirect(comment.snippet.url)
    return render_template('snippets/edit_comment.html', form=form,
                           comment=comment)


@mod.route('/edit/<int:id>/', methods=['GET', 'POST'])
@requires_login
def edit(id):
    snippet = Snippet.query.get(id)
    if snippet is None:
        abort(404)
    if g.user is None or (not g.user.is_admin and snippet.author != g.user):
        abort(401)
    preview = None
    form = dict(title=snippet.title, body=snippet.body,
                category=snippet.category.id)
    if request.method == 'POST':
        form['title'] = request.form['title']
        form['body'] = request.form['body']
        form['category'] = request.form.get('category', type=int)
        if 'preview' in request.form:
            preview = format_creole(request.form['body'])
        elif 'delete' in request.form:
            for comment in snippet.comments:
                db_session.delete(comment)
            db_session.delete(snippet)
            db_session.commit()
            flash(u'Your snippet was deleted')
            return redirect(url_for('snippets.index'))
        else:
            category_id = request.form.get('category', type=int)
            if not form['body']:
                flash(u'Error: you have to enter a snippet')
            else:
                category = Category.query.get(category_id)
                if category is not None:
                    snippet.title = form['title']
                    snippet.body = form['body']
                    snippet.category = category
                    db_session.commit()
                    flash(u'Your snippet was modified')
                    return redirect(snippet.url)
    return render_template('snippets/edit.html',
        snippet=snippet, preview=preview, form=form,
        categories=Category.query.order_by(Category.name).all())


@mod.route('/category/<slug>/')
def category(slug):
    category = Category.query.filter_by(slug=slug).first()
    if category is None:
        abort(404)
    snippets = category.snippets.order_by(Snippet.title).all()
    if request_wants_json():
        return jsonify(category=category.to_json(),
                       snippets=[s.id for s in snippets])
    return render_template('snippets/category.html', category=category,
                           snippets=snippets)


@mod.route('/manage-categories/', methods=['GET', 'POST'])
@requires_admin
def manage_categories():
    categories = Category.query.order_by(Category.name).all()
    if request.method == 'POST':
        for category in categories:
            category.name = request.form['name.%d' % category.id]
            category.slug = request.form['slug.%d' % category.id]
        db_session.commit()
        flash(u'Categories updated')
        return redirect(url_for('.manage_categories'))
    return render_template('snippets/manage_categories.html',
                           categories=categories)


@mod.route('/new-category/', methods=['POST'])
@requires_admin
def new_category():
    category = Category(name=request.form['name'])
    db_session.add(category)
    db_session.commit()
    flash(u'Category %s created.' % category.name)
    return redirect(url_for('.manage_categories'))


@mod.route('/delete-category/<int:id>/', methods=['GET', 'POST'])
@requires_admin
def delete_category(id):
    category = Category.query.get(id)
    if category is None:
        abort(404)
    if request.method == 'POST':
        if 'cancel' in request.form:
            flash(u'Deletion was aborted')
            return redirect(url_for('.manage_categories'))
        move_to_id = request.form.get('move_to', type=int)
        if move_to_id:
            move_to = Category.query.get(move_to_id)
            if move_to is None:
                flash(u'Category was removed in the meantime')
            else:
                for snippet in category.snippets.all():
                    snippet.category = move_to
                db_session.delete(category)
                flash(u'Category %s deleted and entries moved to %s.' %
                      (category.name, move_to.name))
        else:
            category.snippets.delete()
            db_session.delete(category)
            flash(u'Category %s deleted' % category.name)
        db_session.commit()
        return redirect(url_for('.manage_categories'))
    return render_template('snippets/delete_category.html',
                           category=category,
                           other_categories=Category.query
                              .filter(Category.id != category.id).all())


@mod.route('/recent.atom')
def recent_feed():
    feed = AtomFeed(u'Recent Flask Snippets',
                    subtitle=u'Recent additions to the Flask snippet archive',
                    feed_url=request.url, url=request.url_root)
    snippets = Snippet.query.order_by(Snippet.pub_date.desc()).limit(15)
    for snippet in snippets:
        feed.add(snippet.title, unicode(snippet.rendered_body),
                 content_type='html', author=snippet.author.name,
                 url=urljoin(request.url_root, snippet.url),
                 updated=snippet.pub_date)
    return feed.get_response()


@mod.route('/snippets/<int:id>/comments.atom')
def comments_feed(id):
    snippet = Snippet.query.get(id)
    if snippet is None:
        abort(404)
    feed = AtomFeed(u'Comments for Snippet “%s”' % snippet.title,
                    feed_url=request.url, url=request.url_root)
    for comment in snippet.comments:
        feed.add(comment.title or u'Untitled Comment',
                 unicode(comment.rendered_text),
                 content_type='html', author=comment.author.name,
                 url=request.url, updated=comment.pub_date)
    return feed.get_response()

WebTestCreator/Flask/flask_website/templates/snippets/category.html
{% extends "snippets/layout.html" %}
{% block title %}{{ category.name }}{% endblock %}
{% block body %}
  <h2>{{ category.name }}</h2>
  {% if category.count > 3 %}
  <p>
    Here you can find all {{ category.count }} snippets of this
    category.  You can also
  {% else %}
    This category is pretty empty so far.  Why not
  {% endif %}
    <a href="{{ url_for('snippets.new',
      category=category.slug) }}">add a new one</a>.
  {% if snippets %}
  <h3>Snippets in this Category:</h3>
  <ul>
  {% for snippet in snippets %}
    <li><a href="{{ snippet.url }}">{{ snippet.title }}</a>
        <small>({{ snippet.pub_date|dateformat }})</small>
  {% endfor %}
  </ul>
  {% endif %}
{% endblock %}

WebTestCreator/Flask/flask_website/templates/snippets/delete_category.html
{% extends "snippets/layout.html" %}
{% block title %}Snippets Archive{% endblock %}
{% block body %}
  <h2>Delete Category “{{ category.name }}”</h2>
  <p>
    Do you want to delete this category?  And if yes, what should
    happen with the snippets in the category?
  <form action="" method=post>
    <p>
      <select name=move_to>
        <option value="">Delete Snippets</option>
      {%- for category in other_categories %}
        <option value={{ category.id }}>Move to “{{ category.name }}”</option>
      {%- endfor %}
      </select>
    <p>
      <input type=submit value=Delete>
      <input type=submit name=cancel value=Cancel>
  </form>
{% endblock %}

WebTestCreator/Flask/flask_website/templates/snippets/edit.html
{% extends "snippets/layout.html" %}
{% block head %}
  {{ super() }}
  <style type=text/css>
    h1 { background-image: url(/static/edit-snippet.png); }
  </style>
{% endblock %}
{% block title %}Edit Snippet “{{ snippet.title }}”{% endblock %}
{% block body %}
  <script type=text/javascript>
    $(function() {
      $('input[name="delete"]').click(function() {
        if (!confirm("Do you really want to delete this Snippet?\n\n" +
                     "THIS CANNOT BE UNDONE!"))
          return false;
      });
    });
  </script>
  <form action="" method=post>
    <dl>
      <dt>Title:
      <dd><input type=text name=title value="{{ form.title }}" size=40>
      <dt>Category:
      <dd>
        <select name=category>
        {% for category in categories %}
          <option{% if category.id == form.category %} selected{% endif
            %} value={{ category.id }}>{{ category.name }}</option>
        {% endfor %}
        </select>
    </dl>
    <p><textarea name=body cols=40 rows=20>{{ form.body }}</textarea>
    <p>
      <input type=submit value="Edit Snippet">
      <input type=submit name=delete value="Delete">
      <input type=submit name=preview value="Preview">
  </form>
  {% if preview %}
  <div id=preview>
    <h2>Preview</h2>
    {{ preview }}
  </div>
  {% endif %}
{% endblock %}

WebTestCreator/Flask/flask_website/templates/snippets/edit_comment.html
{% extends "snippets/layout.html" %}
{% block title %}Edit Comment {{ comment.title }}{% endblock %}
{% block body %}
  <h2>Edit Comment</h2>
  <script type=text/javascript>
    $(function() {
      $('input[name="delete"]').click(function() {
        if (!confirm("Do you really want to delete this comment?\n\n" +
                     "THIS CANNOT BE UNDONE!"))
          return false;
      });
    });
  </script>
  <form action="" method=post>
    <p>Title: <input type=text name=title value="{{ form.title }}" size=30>
    <p><textarea name=text cols=40 rows=8>{{ form.text }}</textarea>
    <p>
      <input type=submit value="Update Comment">
      <input type=submit name=delete value="Delete">
      <input type=submit name=cancel value="Cancel">
  </form>
{% endblock %}

WebTestCreator/Flask/flask_website/templates/snippets/index.html
{% extends "snippets/layout.html" %}
{% block title %}Snippets Archive{% endblock %}
{% block body %}
  <p>
    Welcome to the Flask snippet archive.  This is the place where anyone
    can drop helpful pieces of code for others to use.
  {% if g.user %}
  <p>
    You're signed in as “<span title="{{ g.user.openid }}">{{ g.user.name
    }}</span>”.  You can <a href="{{ url_for('general.logout')
    }}">sign out</a> here after you're done if you want.  If you want to
    change your OpenID login or display name, head over to the
    <a href="{{ url_for('general.profile') }}">profile</a>.
  {% else %}
  <p>
    In order to add snippets to this page or to add comments, all you need
    is an <a href=http://en.wikipedia.org/wiki/OpenID>OpenID</a> account.
    You can <a href="{{ url_for('general.login') }}">sign in</a> here.
  {% endif %}
  <p>
    Want to share something?  Then add a
    <a href="{{ url_for('.new') }}">new snippet</a>.  Can't find a snippet?
    Try the <a href="{{ url_for('general.search') }}">search</a>.
  <h2>Snippets by Category</h2>
  <ul>
  {% for category in categories %}
    <li><a href="{{ category.url }}">{{ category.name }}</a> ({{ category.count }})
  {% endfor %}
  </ul>
  {% if recent %}
  <h2>Recently Added</h2>
  <ul>
  {% for snippet in recent %}
    <li><a href="{{ snippet.url }}">{{ snippet.title }}</a> in
      <a href="{{ snippet.category.url }}">{{ snippet.category.name }}</a>
  {% endfor %}
  </ul>
  {% endif %}
  {% if g.user.is_admin %}
  <h2>Admin Tools</h2>
  <ul>
    <li><a href="{{ url_for('.manage_categories') }}">Manage categories</a>
  </ul>
  {% endif %}
{% endblock %}

WebTestCreator/Flask/flask_website/templates/snippets/layout.html
{% extends "layout.html" %}
{% block head %}
  {{ super() }}
  <link href="{{ url_for('.recent_feed') }}" rel="alternate" title="Recent Flask Snippets" type="application/atom+xml">
  <style type=text/css>
    h1 { background-image: url({{ url_for('static', filename='snippets.png') }}); }
  </style>
{% endblock %}
{% block body_title %}
  <h1><span>Flask Snippets</span></h1>
{% endblock %}

WebTestCreator/Flask/flask_website/templates/snippets/manage_categories.html
{% extends "snippets/layout.html" %}
{% block title %}Snippets Archive{% endblock %}
{% block body %}
  <h2>Manage Categories</h2>
  {% if categories %}
  <form action="" method=post>
    <table>
      <tr>
        <th>Name
        <th>Slug
        <th>#
        <th>?
    {% for category in categories %}
      <tr>
        <td><input type=text name=name.{{ category.id }} value="{{ category.name }}" size=24>
        <td><input type=text name=slug.{{ category.id }} value="{{ category.slug }}" size=17>
        <td>{{ category.snippets.count() }}
        <td><a href="{{ url_for('.delete_category', id=category.id) }}">delete</a>
    {% endfor %}
    </table>
    <p class=actions>
      <input type=submit value="Update categories">
  </form>
  {% endif %}
  <form action="{{ url_for('.new_category') }}" method=post>
    <p>Or create a new category:
      <input type=text name=name size=30>
      <input type=submit value=Create>
  </form>
{% endblock %}

WebTestCreator/Flask/flask_website/templates/snippets/new.html
{% extends "snippets/layout.html" %}
{% block head %}
  {{ super() }}
  <style type=text/css>
    h1 { background-image: url(/static/new-snippet.png); }
  </style>
{% endblock %}
{% block title %}New Snippet{% endblock %}
{% block body %}
  <p>
    Got something to share?  Here you can create a new snippet and
    publish it here.  By adding the snippet here, you hereby grant
    the user of the snippet all rights.
  <p>
    The syntax used for snippets is <a href="http://www.wikicreole.org/">Creole</a>.
    To highlight Python code or Jinja templates, prefix your code blocks
    with <code>#!python</code>, <code>#!html+jinja</code> or any other
    <a href="http://pygments.org/docs/lexers">Pygments lexer name</a>.
  <p>
    <small>By placing a snippet here you implicitly give it away as being
    a piece of code in the public domain or a similar concept in your
    legislation with similar implications.  Anyone can use the snippet
    freely for anything.</small>
  <form action="" method=post>
    <dl class=formlist>
      <dt>Title:
      <dd><input type=text name=title value="{{ request.form.title }}" size=40>
      <dt>Category:
      <dd>
        <select name=category>
        {% for category in categories %}
          <option{% if category.id == active_category %} selected{% endif
            %} value={{ category.id }}>{{ category.name }}</option>
        {% endfor %}
        </select>
    </dl>
    <p><textarea name=body cols=40 rows=20>{{ request.form.body }}</textarea>
    <p>
      <input type=submit value="Add Snippet">
      <input type=submit name=preview value="Preview">
  </form>
  {% if preview %}
  <div id=preview>
    <h2>Preview</h2>
    {{ preview }}
  </div>
  {% endif %}
{% endblock %}

WebTestCreator/Flask/flask_website/templates/snippets/show.html
{% extends "snippets/layout.html" %}
{% block title %}{{ snippet.title }}{% endblock %}
{% block head %}
  {{ super() }}
  <link href="{{ url_for('.comments_feed', id=snippet.id) }}" rel="alternate" title="Snippet Comments" type="application/atom+xml">
{% endblock %}
{% block body %}
  <h2>{{ snippet.title }}</h2>
  <p class=snippet-author>Posted by {{ snippet.author.name }}
    on {{ snippet.pub_date|datetimeformat }}
    and filed in <a href="{{ snippet.category.url }}">{{ snippet.category.name }}</a>
    {% if snippet.author == g.user or g.user.is_admin %}
      (<a href="{{ url_for('.edit', id=snippet.id) }}">edit</a>)
    {% endif %}
  {{ snippet.rendered_body }}
  <p><small>This snippet by {{ snippet.author.name }} can be used freely for
    anything you like. Consider it public domain.</small>
  {% if snippet.comments or g.user %}
  <div id=comment-box>
  {% if snippet.comments %}
    <h2>Comments</h2>
    <ul class=comments>
      {% for comment in snippet.comments %}
      <li>
        <p class=title>
          {{ comment.title or "Comment" }}
          by {{ comment.author.name }}
          on {{ comment.pub_date|datetimeformat }}
          {% if g.user.is_admin %}
          (<a href="{{ url_for('.edit_comment', id=comment.id) }}">edit</a>)
          {% endif %}
        <div class=body>{{ comment.rendered_text }}</div></li>
      {% endfor %}
    </ul>
  {% endif %}
  {% if g.user %}
  <div id=add-comment>
    <h2>Add Comment</h2>
    <form action="" method=post>
      <p>Title: <input type=text name=title value="{{ request.form.title }}" size=30>
      <p><textarea name=text cols=40 rows=8>{{ request.form.text }}</textarea>
      <p><input type=submit value="Add Comment">
    </form>
  </div>
  {% endif %}
  </div>
  {% endif %}
{% endblock %}